[package]
name = "datify-core"
version = "1.0.0"
entrypoint = "src/main.typ"
authors = ["Jeomhps"]
license = "MIT"
description = "datify-core provides foundational localization data and utilities for date formatting in Typst. Designed for use with the datify package, but reusable in any Typst project needing internationalized date language resources."
repository = "https://github.com/Jeomhps/datify"
compiler = "0.13.1"
exclude = ["tests*"]
